//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetSwissTools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FieldsNameResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldsNameResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetSwissTools.Resources.FieldsNameResource", typeof(FieldsNameResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do credenciador.
        /// </summary>
        public static string AcquirerName {
            get {
                return ResourceManager.GetString("AcquirerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Administrativo.
        /// </summary>
        public static string AdminCode {
            get {
                return ResourceManager.GetString("AdminCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliquota ICMS.
        /// </summary>
        public static string AliqICMS {
            get {
                return ResourceManager.GetString("AliqICMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliquota ICMS-ST.
        /// </summary>
        public static string AliqICMSST {
            get {
                return ResourceManager.GetString("AliqICMSST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite alterar preço.
        /// </summary>
        public static string AllowChangePrice {
            get {
                return ResourceManager.GetString("AllowChangePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite desconto no pedido.
        /// </summary>
        public static string AllowDiscount {
            get {
                return ResourceManager.GetString("AllowDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite cadastrar empresa.
        /// </summary>
        public static string AllowEnterprise {
            get {
                return ResourceManager.GetString("AllowEnterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite parcial.
        /// </summary>
        public static string AllowPartial {
            get {
                return ResourceManager.GetString("AllowPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite alterar cond. pagamento.
        /// </summary>
        public static string AllowPayment {
            get {
                return ResourceManager.GetString("AllowPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anotação.
        /// </summary>
        public static string Annotation {
            get {
                return ResourceManager.GetString("Annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Autorização.
        /// </summary>
        public static string AuthCode {
            get {
                return ResourceManager.GetString("AuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da Autorização.
        /// </summary>
        public static string AuthDate {
            get {
                return ResourceManager.GetString("AuthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACEN.
        /// </summary>
        public static string BACEN {
            get {
                return ResourceManager.GetString("BACEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. mesa.
        /// </summary>
        public static string BoardID {
            get {
                return ResourceManager.GetString("BoardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da mesa.
        /// </summary>
        public static string BoardName {
            get {
                return ResourceManager.GetString("BoardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave de autenticação Cappta.
        /// </summary>
        public static string CapptaKey {
            get {
                return ResourceManager.GetString("CapptaKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca do cartão.
        /// </summary>
        public static string CardBrand {
            get {
                return ResourceManager.GetString("CardBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. cartão.
        /// </summary>
        public static string CardID {
            get {
                return ResourceManager.GetString("CardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Últimos digitos do cartão.
        /// </summary>
        public static string CardLastDigits {
            get {
                return ResourceManager.GetString("CardLastDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. Transportadora.
        /// </summary>
        public static string CarrierID {
            get {
                return ResourceManager.GetString("CarrierID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da categoria.
        /// </summary>
        public static string CatDescription {
            get {
                return ResourceManager.GetString("CatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string CategoryNCM {
            get {
                return ResourceManager.GetString("CategoryNCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string CellPhone {
            get {
                return ResourceManager.GetString("CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigla Internacional.
        /// </summary>
        public static string CIOC {
            get {
                return ResourceManager.GetString("CIOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. cidade.
        /// </summary>
        public static string CityID {
            get {
                return ResourceManager.GetString("CityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da classe.
        /// </summary>
        public static string ClassDescription {
            get {
                return ResourceManager.GetString("ClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificação da empresa.
        /// </summary>
        public static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item do cliente.
        /// </summary>
        public static string ClientItem {
            get {
                return ResourceManager.GetString("ClientItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido do cliente.
        /// </summary>
        public static string ClientOrder {
            get {
                return ResourceManager.GetString("ClientOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (%) Desconto do cliente.
        /// </summary>
        public static string ClientPercDiscount {
            get {
                return ResourceManager.GetString("ClientPercDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ/CPF.
        /// </summary>
        public static string CNPJCPF {
            get {
                return ResourceManager.GetString("CNPJCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COFINS.
        /// </summary>
        public static string COFINS {
            get {
                return ResourceManager.GetString("COFINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cor.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        public static string Complement {
            get {
                return ResourceManager.GetString("Complement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail do contato.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone do contato.
        /// </summary>
        public static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setor do contato.
        /// </summary>
        public static string ContactSector {
            get {
                return ResourceManager.GetString("ContactSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do País.
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. País.
        /// </summary>
        public static string CountryID {
            get {
                return ResourceManager.GetString("CountryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigla do País.
        /// </summary>
        public static string CountryIni {
            get {
                return ResourceManager.GetString("CountryIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do país.
        /// </summary>
        public static string CountryLocalName {
            get {
                return ResourceManager.GetString("CountryLocalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do País.
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de criação.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite de crédito.
        /// </summary>
        public static string CreditLimit {
            get {
                return ResourceManager.GetString("CreditLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite usado.
        /// </summary>
        public static string CreditUsed {
            get {
                return ResourceManager.GetString("CreditUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDD.
        /// </summary>
        public static string DDD {
            get {
                return ResourceManager.GetString("DDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDI.
        /// </summary>
        public static string DDI {
            get {
                return ResourceManager.GetString("DDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de entrega.
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do cartão.
        /// </summary>
        public static string DescCard {
            get {
                return ResourceManager.GetString("DescCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da cond. pagto.
        /// </summary>
        public static string DescriptionPaymentCondition {
            get {
                return ResourceManager.GetString("DescriptionPaymentCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição Forma pagto..
        /// </summary>
        public static string DescriptionPaymentType {
            get {
                return ResourceManager.GetString("DescriptionPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição produto.
        /// </summary>
        public static string DescriptionProd {
            get {
                return ResourceManager.GetString("DescriptionProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiqueta.
        /// </summary>
        public static string DescTag {
            get {
                return ResourceManager.GetString("DescTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Dispositivos.
        /// </summary>
        public static string DevicesCount {
            get {
                return ResourceManager.GetString("DevicesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude de visualização.
        /// </summary>
        public static string DisplayLat {
            get {
                return ResourceManager.GetString("DisplayLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude de visualização.
        /// </summary>
        public static string DisplayLng {
            get {
                return ResourceManager.GetString("DisplayLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string Endereco {
            get {
                return ResourceManager.GetString("Endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Término do evento.
        /// </summary>
        public static string EndEvent {
            get {
                return ResourceManager.GetString("EndEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. Empresa.
        /// </summary>
        public static string EnterpriseId {
            get {
                return ResourceManager.GetString("EnterpriseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. Estabelecimento.
        /// </summary>
        public static string EstabID {
            get {
                return ResourceManager.GetString("EstabID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. Estabelecimento.
        /// </summary>
        public static string EstablishmentId {
            get {
                return ResourceManager.GetString("EstablishmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave do estabelecimento.
        /// </summary>
        public static string EstablishmentKey {
            get {
                return ResourceManager.GetString("EstablishmentKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo do evento.
        /// </summary>
        public static string EventTitle {
            get {
                return ResourceManager.GetString("EventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensão.
        /// </summary>
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familia.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da família.
        /// </summary>
        public static string FamilyDescription {
            get {
                return ResourceManager.GetString("FamilyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familia.
        /// </summary>
        public static string FamilyId {
            get {
                return ResourceManager.GetString("FamilyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. campo.
        /// </summary>
        public static string FieldID {
            get {
                return ResourceManager.GetString("FieldID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho do arquivo.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxa financeira.
        /// </summary>
        public static string FinancialTaxes {
            get {
                return ResourceManager.GetString("FinancialTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frete pago por.
        /// </summary>
        public static string FreightPaidBy {
            get {
                return ResourceManager.GetString("FreightPaidBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do frete.
        /// </summary>
        public static string FreightValue {
            get {
                return ResourceManager.GetString("FreightValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da grupo.
        /// </summary>
        public static string GroupDescription {
            get {
                return ResourceManager.GetString("GroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBGE.
        /// </summary>
        public static string IBGE {
            get {
                return ResourceManager.GetString("IBGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        public static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id. ERP.
        /// </summary>
        public static string IdERP {
            get {
                return ResourceManager.GetString("IdERP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IE.
        /// </summary>
        public static string IE {
            get {
                return ResourceManager.GetString("IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho imagem.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigla.
        /// </summary>
        public static string Initials {
            get {
                return ResourceManager.GetString("Initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcelas.
        /// </summary>
        public static string Installments {
            get {
                return ResourceManager.GetString("Installments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPI.
        /// </summary>
        public static string IPI {
            get {
                return ResourceManager.GetString("IPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluído.
        /// </summary>
        public static string IsComplete {
            get {
                return ResourceManager.GetString("IsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orçamento.
        /// </summary>
        public static string IsProposal {
            get {
                return ResourceManager.GetString("IsProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Público.
        /// </summary>
        public static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso.
        /// </summary>
        public static string IsSuccess {
            get {
                return ResourceManager.GetString("IsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item do pedido.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nível item do pedido.
        /// </summary>
        public static string ItemLevel {
            get {
                return ResourceManager.GetString("ItemLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimo login.
        /// </summary>
        public static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da lista.
        /// </summary>
        public static string ListDescription {
            get {
                return ResourceManager.GetString("ListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da lista.
        /// </summary>
        public static string ListName {
            get {
                return ResourceManager.GetString("ListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. Ped. Venda Principal.
        /// </summary>
        public static string MainOrderID {
            get {
                return ResourceManager.GetString("MainOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo do arquivo.
        /// </summary>
        public static string MimeType {
            get {
                return ResourceManager.GetString("MimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de modificação.
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVA.
        /// </summary>
        public static string MVA {
            get {
                return ResourceManager.GetString("MVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do cartão.
        /// </summary>
        public static string NameCard {
            get {
                return ResourceManager.GetString("NameCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do campo.
        /// </summary>
        public static string NameField {
            get {
                return ResourceManager.GetString("NameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude de navegação.
        /// </summary>
        public static string NavLat {
            get {
                return ResourceManager.GetString("NavLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude de navegação.
        /// </summary>
        public static string NavLng {
            get {
                return ResourceManager.GetString("NavLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCM.
        /// </summary>
        public static string NCM {
            get {
                return ResourceManager.GetString("NCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apelido do aparelho.
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome fantasia.
        /// </summary>
        public static string NomeFantasia {
            get {
                return ResourceManager.GetString("NomeFantasia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Sequencial Único.
        /// </summary>
        public static string NSU {
            get {
                return ResourceManager.GetString("NSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string Num {
            get {
                return ResourceManager.GetString("Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. País internacional.
        /// </summary>
        public static string NumericCode {
            get {
                return ResourceManager.GetString("NumericCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origem da criação.
        /// </summary>
        public static string OriginCreate {
            get {
                return ResourceManager.GetString("OriginCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origem do login.
        /// </summary>
        public static string OriginLogin {
            get {
                return ResourceManager.GetString("OriginLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qtd. por embalagem.
        /// </summary>
        public static string PackageQTD {
            get {
                return ResourceManager.GetString("PackageQTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme a senha.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cond. pagto. padrão.
        /// </summary>
        public static string PayConditionId {
            get {
                return ResourceManager.GetString("PayConditionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (%)Comissão.
        /// </summary>
        public static string PercCommission {
            get {
                return ResourceManager.GetString("PercCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (%)Desconto.
        /// </summary>
        public static string PercDiscount {
            get {
                return ResourceManager.GetString("PercDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (%) Desconto de preço.
        /// </summary>
        public static string PercDiscountPrice {
            get {
                return ResourceManager.GetString("PercDiscountPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (%) Incremento de preço.
        /// </summary>
        public static string PercIncreasePrice {
            get {
                return ResourceManager.GetString("PercIncreasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (%)IPI.
        /// </summary>
        public static string PercIPI {
            get {
                return ResourceManager.GetString("PercIPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (%)Max. desconto.
        /// </summary>
        public static string PercMaxDiscount {
            get {
                return ResourceManager.GetString("PercMaxDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIS.
        /// </summary>
        public static string PIS {
            get {
                return ResourceManager.GetString("PIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posição da lista.
        /// </summary>
        public static string PositionList {
            get {
                return ResourceManager.GetString("PositionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. Produto.
        /// </summary>
        public static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. produto.
        /// </summary>
        public static string ProductKey {
            get {
                return ResourceManager.GetString("ProductKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo do produto.
        /// </summary>
        public static string ProductTypeId {
            get {
                return ResourceManager.GetString("ProductTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de referência.
        /// </summary>
        public static string QuantityReference {
            get {
                return ResourceManager.GetString("QuantityReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramal.
        /// </summary>
        public static string Ramal {
            get {
                return ResourceManager.GetString("Ramal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razão social.
        /// </summary>
        public static string RazaoSocial {
            get {
                return ResourceManager.GetString("RazaoSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indice de receptividade.
        /// </summary>
        public static string ReceptivityIndex {
            get {
                return ResourceManager.GetString("ReceptivityIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. Região de vendas.
        /// </summary>
        public static string RegionId {
            get {
                return ResourceManager.GetString("RegionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo obrigatório.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo da revisão.
        /// </summary>
        public static string RevisionReason {
            get {
                return ResourceManager.GetString("RevisionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG.
        /// </summary>
        public static string RG {
            get {
                return ResourceManager.GetString("RG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fator U.M. Venda.
        /// </summary>
        public static string SaleFactor {
            get {
                return ResourceManager.GetString("SaleFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.M. Venda.
        /// </summary>
        public static string SaleUnit {
            get {
                return ResourceManager.GetString("SaleUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setor.
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. configuração.
        /// </summary>
        public static string SettingsID {
            get {
                return ResourceManager.GetString("SettingsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dias para entrega.
        /// </summary>
        public static string ShippingDays {
            get {
                return ResourceManager.GetString("ShippingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início do evento.
        /// </summary>
        public static string StartEvent {
            get {
                return ResourceManager.GetString("StartEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. estado.
        /// </summary>
        public static string StateID {
            get {
                return ResourceManager.GetString("StateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do estado.
        /// </summary>
        public static string StateName {
            get {
                return ResourceManager.GetString("StateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status CRM.
        /// </summary>
        public static string StatusCRM {
            get {
                return ResourceManager.GetString("StatusCRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status da empresa.
        /// </summary>
        public static string StatusEnterprise {
            get {
                return ResourceManager.GetString("StatusEnterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Pagamento.
        /// </summary>
        public static string StatusPayment {
            get {
                return ResourceManager.GetString("StatusPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status pedido.
        /// </summary>
        public static string StatusPed {
            get {
                return ResourceManager.GetString("StatusPed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status da sicronização.
        /// </summary>
        public static string StatusSinc {
            get {
                return ResourceManager.GetString("StatusSinc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo de estoque.
        /// </summary>
        public static string StockBalance {
            get {
                return ResourceManager.GetString("StockBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token CNPJ.
        /// </summary>
        public static string TokenCNPJ {
            get {
                return ResourceManager.GetString("TokenCNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor total.
        /// </summary>
        public static string TotalValue {
            get {
                return ResourceManager.GetString("TotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor total comissão.
        /// </summary>
        public static string TotalValueCommission {
            get {
                return ResourceManager.GetString("TotalValueCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor total do desconto.
        /// </summary>
        public static string TotalValueDiscount {
            get {
                return ResourceManager.GetString("TotalValueDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor total c/ desconto.
        /// </summary>
        public static string TotalValueWithDiscount {
            get {
                return ResourceManager.GetString("TotalValueWithDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo do endreço.
        /// </summary>
        public static string TypeAddress {
            get {
                return ResourceManager.GetString("TypeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo do cartão.
        /// </summary>
        public static string TypeCard {
            get {
                return ResourceManager.GetString("TypeCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição tipo do produto.
        /// </summary>
        public static string TypeDescription {
            get {
                return ResourceManager.GetString("TypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo da empresa.
        /// </summary>
        public static string TypeEnterprise {
            get {
                return ResourceManager.GetString("TypeEnterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo do campo.
        /// </summary>
        public static string TypeField {
            get {
                return ResourceManager.GetString("TypeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo do produto.
        /// </summary>
        public static string TypeId {
            get {
                return ResourceManager.GetString("TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. Forma pagto.
        /// </summary>
        public static string TypePayID {
            get {
                return ResourceManager.GetString("TypePayID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        public static string UF {
            get {
                return ResourceManager.GetString("UF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave única.
        /// </summary>
        public static string UniqueKey {
            get {
                return ResourceManager.GetString("UniqueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.M..
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da unidade de medida.
        /// </summary>
        public static string UnitDescription {
            get {
                return ResourceManager.GetString("UnitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. usuário.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave do usuário.
        /// </summary>
        public static string UserKey {
            get {
                return ResourceManager.GetString("UserKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo do usuário.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visível.
        /// </summary>
        public static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP Término.
        /// </summary>
        public static string ZIPCodeEnd {
            get {
                return ResourceManager.GetString("ZIPCodeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP Início.
        /// </summary>
        public static string ZIPCodeStart {
            get {
                return ResourceManager.GetString("ZIPCodeStart", resourceCulture);
            }
        }
    }
}
